steps:
  # Install
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Test
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test:unit']

  # Build
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Push the Docker image to Container Registry
  - name: 'gcr.io/project-p5-game/jogo-p5'
    args: ['deploy']

